import type { Metadata } from "next";
import "./globals.css";
import Lightfall from "./BgComponents/AnimatedBg";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased dark">
      <body className="min-h-screen relative bg-[#0d0e12] text-white overflow-x-hidden">
        
        {/* 1. FIXED BACKGROUND CONTAINER: Spans the exact viewport window at z-0 */}
        <div className="fixed inset-0 w-full h-full z-0 pointer-events-none">
          <Lightfall
            colors={['#A6C8FF', '#5227FF', '#FF9FFC']}
            backgroundColor="#0A29FF"
            speed={0.5}
            streakCount={2}
            streakWidth={1}
            streakLength={1}
            glow={1}
            density={0.6}
            twinkle={1}
            zoom={3}
            backgroundGlow={0.5}
            opacity={1}
            mouseInteraction
            mouseStrength={0.5}
            mouseRadius={1}
          />
        </div>

        {/* 2. ISOLATED APP CONTENT LAYER: Pushed on top at z-10 with native flow */}
        <main className="relative z-10 w-full min-h-screen">
          {children}
        </main>

      </body>
    </html>
  );
}
